FROM node:alpine

# Create app directory within container
WORKDIR /usr/src/app

# Install dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./


# FROM base as production


RUN npm run build

CMD ["npm", "start"]